//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string IdBill { get; set; }
        public string IdFlower { get; set; }
        public Nullable<double> IntoMoney { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Flower Flower { get; set; }
    }
}
