//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluate
    {
        public string IdEvaluate { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Star { get; set; }
        public string Imgae { get; set; }
        public string IdFlower { get; set; }
        public string IdClient { get; set; }
    }
}
