//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHoa.Models
{
    using System;
    
    public partial class GetFlowerTypePercentage_Result1
    {
        public string FlowerType { get; set; }
        public Nullable<int> FlowerCount { get; set; }
    }
}
